pull_request_rules:
    -   name: Automatic merge on double-approval
        conditions:
            - "#approved-reviews-by>=2"
        actions:
            merge:
                method: merge
    -   name: Merge pull requests from pyup if CI passes
        conditions:
            - author=pyup-bot
            - status-success=continuous-integration/travis-ci/pr
        actions:
            merge:
                method: squash
